// <auto-generated />
namespace Monage.Migrations {
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddExpenses : IMigrationMetadata {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddExpenses));

        string IMigrationMetadata.Id {
            get { return "201406050401464_AddExpenses"; }
        }

        string IMigrationMetadata.Source {
            get { return null; }
        }

        string IMigrationMetadata.Target {
            get { return Resources.GetString("Target"); }
        }
    }
}
