// <auto-generated />
namespace Monage.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddExpenses_Indexes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddExpenses_Indexes));
        
        string IMigrationMetadata.Id
        {
            get { return "201406050404008_AddExpenses_Indexes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
