// <auto-generated />
namespace Monage.Migrations {
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ConvertToDecimal : IMigrationMetadata {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConvertToDecimal));

        string IMigrationMetadata.Id {
            get { return "201408172205583_ConvertToDecimal"; }
        }

        string IMigrationMetadata.Source {
            get { return null; }
        }

        string IMigrationMetadata.Target {
            get { return Resources.GetString("Target"); }
        }
    }
}
